### DISCUSSION TITLE
edenx module在github workflow上发包后会缺少标签，是我的配置有啥问题吗

### DISCUSSION THREAD

**Discussion by asurance** [web-infra-dev/modern.js#6483] [Q&A]
workflow 配置如下，本地打包是正常的
```yaml
name: Public Packages

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm build

      - name: Test Package
        run: pnpm test

      - name: Publish Package
        run: pnpm release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

        # 发现缺少标签后加了这步但是也没用
      - name: Push Tag
        run: git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
