### ISSUE TITLE
[Bug]: 输出node_modules中的SCSS中的字体资源链接时使用了错误的分隔符

### ISSUE THREAD

**Issue by KotoriK** [web-infra-dev/modern.js#2981]
### 版本信息

```sh
├── @modern-js/app-tools@2.5.0 -> .\node_modules\.pnpm\registry.npmmirror.com+@modern-js+app-tools@2.5.0_lb6du3saekb5anf2gjv3wxj3oq\node_modules\@modern-js\app-tools
└─┬ @modern-js/runtime@2.5.0 -> .\node_modules\.pnpm\registry.npmmirror.com+@modern-js+runtime@2.5.0_xt5rz2p4kfiafm7tqbw5ojpmci\node_modules\@modern-js\runtime
  └── @modern-js/app-tools@2.5.0 deduped -> .\node_modules\.pnpm\registry.npmmirror.com+@modern-js+app-tools@2.5.0_lb6du3saekb5anf2gjv3wxj3oq\node_modules\@modern-js\app-tools
```

## 问题详情
涉事scss如下（来自```element-theme-chalk/src/icon.scss```）
```scss
@font-face {
  font-family: 'element-icons';
  src: url('#{$--font-path}/element-icons.woff') format('woff'), /* chrome, firefox */
       url('#{$--font-path}/element-icons.ttf') format('truetype'); /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
  font-weight: normal;
  font-display: $--font-display;
  font-style: normal;
}
```
实际输出的css是：
```css
@font-face {
  font-family: "element-icons";
  src: url(/static\font\element-icons.ff18efd1.woff) format("woff"), url(/static\font\element-icons.f1a45d74.ttf) format("truetype"); /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
  font-weight: normal;
  font-display: "auto";
  font-style: normal;
}
```
查看了一下```dist/static/font```，相关字体有打包，纯粹是因为路径的分隔符不对而无法加载。

## 其他信息

1. Modern v1.x没有这个问题。
2. 生产构建产物(使用```modern build```而非```modern dev```）没有这个问题
3. $--font-path的值： ```$--font-path: 'fonts' !default;```
4. modern.config.ts

```ts
import { dirname } from 'path';
import appTools, { defineConfig } from '@modern-js/app-tools';
import { VanillaExtractPlugin } from '@vanilla-extract/webpack-plugin';
import { DefinePlugin } from 'webpack';
import { commitHash } from './scripts/commit_hash';
// https://modernjs.dev/docs/apis/config/overview

function resolveModule(moduleName: string) {
  return dirname(require.resolve(moduleName));
}
export default defineConfig({
  runtime: {
    router: true,
    state: false,
  },
  output: {
    disableNodePolyfill: true,
    polyfill: 'usage',
  },
  html: {
  },
  plugins: [appTools()],
  tools: {
    babel: (config, { addPlugins, addIncludes }) => {
      addPlugins(['@babel/plugin-proposal-class-properties']);
      addIncludes(
        [
        ].map(resolveModule),
      );
    },
    webpack: {
      plugins: [
        new VanillaExtractPlugin(),
        new DefinePlugin({
          COMMIT: `"${commitHash}"`,
        }),
      ],
    },
    devServer: {

    },
  },
});

```

### 复现链接

无

### 复现步骤

1. 引入```element-theme-chalk/src/icon.scss```
2. 执行```modern dev```（```modern build```没有此问题）
